project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap
    link-external-newwindow: true
    


website:
  title: "Reporting on the Texas Legislature: A Data Journalism Toolkit"
  page-navigation: true
  bread-crumbs: true
  navbar:
    background: dark
    search: false
    right: 
      - icon: github
        href: https://github.com/sarahbrager
      - icon: linkedin
        href: https://www.linkedin.com/in/sarah-brager/
      - icon: envelope
        href: mailto:sarahbrager@utexas.edu
  page-footer: 
    background: light
    left: This website was published using GitHub pages.
      
  sidebar:
    style: "docked"
    search: false
    background: light
    contents:
      - text: "Home"
        href: index.qmd
      - text: "What is Data Journalism?"
        href: introduction.qmd
      - text: "Setting Up"
        href: about.qmd
      - text: "Sourcing the Data"
        href: sourcing.qmd
      - text: "Cleaning the Data"
        href: cleaning.qmd
      - text: "Analyzing the Data"
        href: analysis.qmd
      - text: "Visualizing the Data"
        href: charting.qmd
      - text: "Reporting with the Data"
        href: reporting.qmd
      - text: "Additional Resources"
        href: resources.qmd
      - text: "Meet the Author"
        href: author.qmd
        


editor: visual

