project:
  type: website
  output-dir: docs

title: "About This Project"
# add headshot later
toc: false
about: 
  template: solana


website:
  title: "Reporting on the Texas Legislature: A Data Journalism Toolkit"
  navbar:
    background: dark
    search: false
    right: 
      - icon: github
        href: https://github.com/sarahbrager
      - icon: linkedin
        href: https://www.linkedin.com/in/sarah-brager/
      - icon: envelope
        href: mailto:sarahbrager@utexas.edu
  page-footer: 
    background: light
    left: This website was built with # add R and Quarto icons later
      
  sidebar:
    style: "docked"
    search: false
    background: secondary
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About This Project"
        href: about.qmd
      - text: "Data Journalism Basics"
        href: introduction.qmd
      - text: "Sourcing Our Data"
        href: sourcing.qmd
      - text: "Cleaning the Data"
        href: cleaning.qmd
      - text: "Analyzing the Data"
        href: analysis.qmd
      - text: "Making Simple News Graphics"
        href: charting.qmd
      - text: "Reporting With This Data"
        href: reporting.qmd
      - text: "Additional Resources"
        href: resources.qmd
      - text: "Meet the Author"
        href: author.qmd
        

format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5em
    theme: yeti
    css: styles.scss
    toc: true

editor: visual

