project:
  type: website
  output-dir: docs

title: "About This Project"
# add headshot later
toc: false
about: 
  template: jolla
  links: 
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/sarah-brager/
    - icon: github
      text: Github
      href: https://github.com/sarahbrager 
    - icon: envelope
      text: Email
      href: mailto:sarahbrager@utexas.edu


website:
  title: "Reporting on the Texas Legislature: A Data Journalism Toolkit"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      
  sidebar:
    style: "docked"
    search: false
    contents: 
      - text: "About This Project"
        href: about.qmd
      - text: "Data Journalism Basics"
        href: introduction.qmd
      - text: "Sourcing Our Data"
        href: sourcing.qmd
      - text: "Cleaning the Data"
        href: cleaning.qmd
      - text: "Analyzing the Data"
        href: analysis.qmd
      - text: "Making Simple News Graphics"
        href: charting.qmd
      - text: "Reporting With This Data"
        href: reporting.qmd
      - text: "Additional Resources"
        href: resources.qmd
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

