---
title: "Incorporating the Data in Your Reporting"
format: html
---

### So what now?

You might be thinking – Okay, I crunched all of those numbers, but how can I actually apply them to my work as a journalist?

If you're a journalist covering Texas politics and policy making in any way, these statistics could provide great context for readers about the current legislative session. Whether you're doing a broad overview of trends from the session or reporting on a specific bill, you can come back to this analysis and pull information to weave into your article.

#### [Some tips for writing with numbers]{.underline}

-   Don't include more than 2-3 stats in a paragraph.

-   Use comparisons to help people understand. For example, if you wrote about the total number of bills filed this session, compare that stat to previous sessions so readers understand if it's much higher/lower or about the same.

-   Find human sources who can add context to the data. Data journalism doesn't mean the stats are your only source, they're just an extra layer of reporting.

-   When possible, include a chart that visually explains what you're talking about in the story. Some people process information better with visuals, and most readers nowadays engage more with graphics than big blocks of text.

    -   Plus, you can add extra detail about the data to the caption of your chart, which you may not have had room for in the actual story.

-   Keep things simple. Readers tend to get lost in jargon or too much detail. Convey all of the important information, but do so concisely.

#### [What if I'm a journalist in a different state?]{.underline}

You can run this exact analysis using LegiScan data from any other state! Follow the instructions on the Sourcing page, but select your state of choice when downloading the data.

### Story ideas based on the data

-   Compare results from the current session to the previous session by downloading CSVs for the 88th legislature and running the same analysis. This could add some great data context to an article about legislative actions/priorities this year compared to 2023.

-   You could also do the same thing as above but over the past decade! This would require more analysis work, but it could make for an interesting long-form data project.

-   If you're reporting on policy priorities for lawmakers this session, see how frequently certain policy topics came up by filtering for keywords in the bill descriptions. This could also make for an interesting comparison over time; for instance, when in Texas did we start to see lawmakers file bills focusing on DEI? Have the number of DEI-related bills grown since then?

-   If you're part of a regional news outlet covering a specific lawmaker, use the analysis to track how "active" they've been since being elected. Are they sponsoring a lot of legislation? Then use additional reporting to explain the trend.

-   Run an analysis on another state and compare it to Texas. How do bill topics compare in red states vs. blue states?

-   Report on Capitol efficiency by monitoring the status of bills. How many bills are actually clearing the House and the Senate this session, and how does that compare to previous years? Are there simply too many bills to get to? Is there too much gridlock in Congress?

Again, none of these stories can be told using the data alone. Find all of the expert and stakeholder sources that you normally would, and add the stats from your analysis for additional context.

### Conclusion 

Clearly there's so much you can do with LegiScan data, both in terms of analysis and reporting, but hopefully this toolkit served as a good introduction to data journalism and sparked some interest in covering Texas politics in a data-driven way.

I encourage you to run this analysis again at some point to get more practice. You could continue to monitor how bills progress in the 89th Texas session, analyze a previous Texas session, or analyze a completely different state. The best way to get more comfortable with R syntax and functions is to just keep running code.

Once you've practiced with this LegiScan tutorial some more, try experimenting with a new data set! There are tons of public data portals that allow you to download CSVs. Obviously the cleaning and analysis instructions on this website won't match exactly, so there might be a bit of trial and error, but all of the functions you learned are standard for working with any data.

See the next section for resources about using R, analyzing data with other tools (like spreadsheets), troubleshooting code errors, and more. You got this!
