---
title: "Downloading Data from LegiScan"
format: html
---

Include a video tutorial at the top of this page.

All of the data for this tutorial comes from LegiScan, a real-time and nonpartisan legislative tracking service available to the public. While this project only focuses on data from the Texas Legislature, LegiScan has data sets from all 50 states. The data is updated weekly on Sundays.

LegiScan is a good example of the type of public database that a data journalist might pull from frequently. There are lots of other resources available online with data from government agencies. If you're a journalist covering the environment, for example, you might try xyz.

### Steps for downloading 

#### 1. Go to legiscan.com 

#### 2. Create a login 

LegiScan requires you to create a username and password to download datasets. This is completely free. Create an account, and then click on the "Datasets" tab at the top of the page.

#### 3. Filter for Texas 

Select "TX" to view all of LegiScan's data from the Texas Legislature. You'll see their data goes back to 2010 (the 81st Texas Legislature). For now, we're just going to focus on the 89th session, which is the current one for 2025-2026.

#### 4. Download the CSV file 

In the top right corner of the data library is a column that says "CSV Basic." This is the type of file we want to download.

::: callout-note
CSV stands for "comma separated values," which is just one of many ways a dataset can be stored. This is a pretty common file type for working with data, so if you're ever downloading data from other sources, you'll likely see this as an option.
:::

Click on the red "CSV" button for the 89th session to download the file to your computer. It should be a compressed folder filled with multiple csv files.

::: {.callout-tip title="Tip"}
I recommend immediately renaming the folder to something that's easy for you to find later. For example: "tx-bills-89"
:::

#### 5. Take a look at the dataset 
